version: '3.7'

services:

  db:
    image: postgres
    restart: on-failure
    container_name: db
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    env_file:
      - .env
    volumes:
      - ./db/initdb.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - internal

  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - default
      - internal

networks:
  default:
    external: true
    name: quero-default
  internal:
    internal: true